import React, { useState } from 'react';
import { ProjectState, ArchitecturePlan } from '../types';
import { generateArchitecture } from '../services/geminiService';
import { Sparkles, Server, Database, Globe, Layers, ArrowRight, Cpu, Box } from 'lucide-react';

interface PhasePlanProps {
  projectState: ProjectState;
  setProjectState: React.Dispatch<React.SetStateAction<ProjectState>>;
  onNext: () => void;
}

const PhasePlan: React.FC<PhasePlanProps> = ({ projectState, setProjectState, onNext }) => {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGeneratePlan = async () => {
    setIsGenerating(true);
    try {
      const plan = await generateArchitecture(projectState.spec);
      setProjectState(prev => ({ ...prev, plan }));
    } catch (error) {
      alert("Failed to generate architecture plan.");
    } finally {
      setIsGenerating(false);
    }
  };

  const hasPlan = projectState.plan.components.length > 0;

  return (
    <div className="space-y-10 animate-in fade-in slide-in-from-bottom-8 duration-700">
      
      {!hasPlan ? (
        <div className="flex flex-col items-center justify-center h-[500px] bg-white rounded-[2rem] border border-zinc-100 shadow-sm">
          <div className="w-20 h-20 bg-zinc-50 rounded-3xl flex items-center justify-center mb-8 shadow-inner">
            <Layers className="w-8 h-8 text-zinc-400" />
          </div>
          <h2 className="text-2xl font-medium text-zinc-900 mb-3 tracking-tight">Technical Architecture</h2>
          <p className="text-zinc-500 max-w-md text-center mb-10 font-light leading-relaxed">
            The AI will now analyze the specifications to propose a scalable, modern technology stack and system design.
          </p>
          <button 
            onClick={handleGeneratePlan}
            disabled={isGenerating}
            className={`flex items-center gap-3 px-8 py-4 rounded-full font-medium text-white transition-all transform duration-300 ${
              isGenerating ? 'bg-zinc-300 cursor-wait' : 'bg-zinc-900 hover:scale-105 hover:shadow-xl hover:shadow-zinc-900/20 active:scale-95'
            }`}
          >
            {isGenerating ? (
               <>
                 <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                 <span>Architecting...</span>
               </>
            ) : 'Generate Architecture Plan'}
          </button>
        </div>
      ) : (
        <>
          {/* Overview & Stack */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-2 bg-white p-8 rounded-[2rem] border border-zinc-100 shadow-[0_4px_20px_rgba(0,0,0,0.02)]">
              <h3 className="text-sm font-bold uppercase tracking-widest text-zinc-400 mb-6 flex items-center gap-2">
                System Overview
              </h3>
              <p className="text-zinc-600 leading-relaxed font-light text-lg">{projectState.plan.overview}</p>
            </div>
            
            <div className="bg-zinc-900 p-8 rounded-[2rem] shadow-xl shadow-zinc-900/10 flex flex-col justify-between">
               <div>
                  <h3 className="text-sm font-bold uppercase tracking-widest text-zinc-500 mb-6">Tech Stack</h3>
                  <div className="flex flex-wrap gap-2">
                    {projectState.plan.stack.map((tech, i) => (
                      <span key={i} className="px-4 py-2 bg-zinc-800 text-zinc-200 text-sm font-medium rounded-xl border border-zinc-700/50">
                        {tech}
                      </span>
                    ))}
                  </div>
               </div>
               <div className="mt-8 pt-8 border-t border-zinc-800 flex items-center gap-2 text-zinc-500 text-xs">
                 <Box className="w-4 h-4" />
                 Generated by Gemini 2.5 Flash
               </div>
            </div>
          </div>

          {/* Component Diagram Simulation */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
            {/* Components List */}
            <div className="space-y-6">
              <h3 className="text-xs font-bold uppercase tracking-widest text-zinc-400 ml-1">Core Components</h3>
              {projectState.plan.components.map((comp, i) => (
                <div key={i} className="flex gap-6 p-6 bg-white rounded-3xl border border-zinc-100 hover:border-zinc-200 hover:shadow-[0_8px_30px_rgba(0,0,0,0.04)] transition-all duration-300 group">
                  <div className={`w-14 h-14 rounded-2xl flex items-center justify-center shrink-0 transition-colors ${
                    comp.type === 'Frontend' ? 'bg-zinc-50 text-zinc-900' :
                    comp.type === 'Backend' ? 'bg-zinc-50 text-zinc-900' :
                    comp.type === 'Database' ? 'bg-zinc-50 text-zinc-900' :
                    'bg-zinc-50 text-zinc-900'
                  }`}>
                    {comp.type === 'Frontend' && <Globe className="w-6 h-6 stroke-1" />}
                    {comp.type === 'Backend' && <Server className="w-6 h-6 stroke-1" />}
                    {comp.type === 'Database' && <Database className="w-6 h-6 stroke-1" />}
                    {comp.type === 'Service' && <Layers className="w-6 h-6 stroke-1" />}
                  </div>
                  <div>
                    <h4 className="font-semibold text-zinc-900 text-lg mb-1">{comp.name}</h4>
                    <span className="text-xs font-mono text-zinc-400 mb-2 block">{comp.tech}</span>
                    <p className="text-sm text-zinc-500 font-light leading-relaxed">{comp.description}</p>
                  </div>
                </div>
              ))}
            </div>

            {/* Database Schema */}
            <div className="space-y-6">
               <h3 className="text-xs font-bold uppercase tracking-widest text-zinc-400 ml-1">Data Schema</h3>
               <div className="bg-[#18181b] p-8 rounded-3xl border border-zinc-800 font-mono text-sm text-zinc-400 overflow-x-auto whitespace-pre-wrap leading-loose shadow-2xl">
                 {projectState.plan.databaseSchema}
               </div>
            </div>
          </div>

          <div className="flex justify-end pt-8">
             <button 
                onClick={onNext}
                className="flex items-center gap-2 px-8 py-4 bg-white text-zinc-900 border border-zinc-200 rounded-full hover:bg-zinc-50 transition-all font-medium shadow-sm hover:shadow-md active:scale-95"
              >
                <span>Break Down Tasks</span>
                <ArrowRight className="w-4 h-4" />
              </button>
          </div>
        </>
      )}
    </div>
  );
};

export default PhasePlan;